package ap.project.model.enums;

import ap.project.model.App;

public enum Texts {
    Yes("Yes", "Are"),
    No("No", "Na"),
    NowPressKey("Now press the key you want", "Kelidi ke mikhai roo entekhab kon"),
    OK("Ok", "Hale"),
    InvalidUsername("Username is invalid", "Username motabar nist"),
    InvalidPassword("Password is invalid", "Password motabar nist"),
    FirstSchool("What is your first school name?", "esm avalin madresat chi bood?"),
    Subimt("Submit", "boroo"),
    EnterYourNewPass("Enter your new password","Ramz jadid roo vared kon"),
    WrongAnswer("Wrong answer!", "eshtebahe!"),
    Guest("Guest", "Mehman"),
    UserAlreadyRegistered("Username already exists with this username.", "Ye karbar dighe ba in nam vojood dare"),
    Score("Score", "Emtiaz"),
    PasswordChanged("Password changed successfully", "Ramz ba movafaghian avaz shod"),
    SelectGameTime("Select A Game Time!!", "Ye Zaman entekhab kon!"),
    SelectGun("Select A Gun First!!", "Ye Tofang entekhab kon!"),
    SelectChar("Select A Character First!!", "Ye karakter entekhab kon!"),
    NotLoggedIn("You are not logged in!", "Login nakardi ke"),
    YouLose("YOU LOSE!", "Bakhtii!"),
    YouWin("YOU WIN!", "Bordi!!"),
    Username4Character("Username should be at least 4 characters", "Namkarbari bayad hadeaghal 4 harf bashe!"),
    Password8Character("Password should be at least 8 characters", "Password bayad hadeaghal 8 harf bashe!"),
    PasswordOneLower("Password should contain at least one lowercase letter", "Password bayad ye doone harf kochik dashe base!"),
    PasswordOneUpper("Password should contain at least one uppercase letter", "Password bayad ye doone harf bozorg dashe base!"),
    PasswordOneDigit("Password should contain at least one digit", "Password bayad ye adad dashte base!"),
    PasswordSpecialChar("Password should contain at least one special character", "Password bayad ye karakter makhsoos dashte base!"),
    BackToMainMenu("Back To Main Menu", "Boro be menu asli"),
    Username("Username", "Namkarbari"),
    Kills("Kills", "Koshteha"),
    SurvivalTime("Survival Time", "Zamane baqamonde"),
    Seconds("seconds", "sanie"),
    LEVEL("Level", "Level"),
    ABILITY("Ability", "Tavanayi"),
    AMMO("Ammo", "Gololeh"),
    PAUSE("Pause", "Pause"),
    RESUME("Resume", "Edame"),
    EXIT("Exit", "Khorooj"),
    HEROS("Heros:", "Ghahraman-ha:"),
    HP("HP", "HP"),
    SPEED("Speed", "Sorat"),
    KEY_SETTINGS("Key Settings:", "Tanzimate Kelid:"),
    KEY_UP("Key up", "Kelid bala"),
    KEY_DOWN("Key down", "Kelid payin"),
    KEY_LEFT("Key left", "Kelid chap"),
    KEY_RIGHT("Key right", "Kelid rast"),
    RELOAD("Reload", "Reload"),
    CHEAT_CODES("Cheat Codes:", "Code-haye cheat:"),
    CHEAT_M("Press M reduce 1 minute from time!", "M bezan, 1 daghighe az zaman kam mishe!"),
    CHEAT_N("Press N to level up!", "N bezan, level mirafae!"),
    CHEAT_L("Press L to increase you HP!", "L bezan, HP miaad bala!"),
    CHEAT_P("Press P to summon the ELDER!", "P bezan, Boss ro seda kon!"),
    CHEAT_O("Press O to increase fire rate!", "O bezan, sorat tir bala mire!"),
    ABILITIES("Abilities:", "Tavanmandi-ha:"),
    BACK("Back", "Bargasht"),
    WELCOME("Welcome", "Khosh oomadi"),
    SCORE("Score: ", "Emtiaz: "),
    PLAY("Play", "Bazi"),
    PLAY_SAVED_GAME("Play Saved Game", "Baziye Zakhire shode"),
    SCOREBOARD("Scoreboard", "Rizkar"),
    SETTINGS("Settings", "Tanzimat"),
    HINT_MENU("Hint Menu", "Rahnamaha"),
    LOGOUT("Logout", "Khorooj"),
    PROFILE("Profile", "Profile"),
    Resume("Resume", "Edame"),
    GiveUp("Give Up", "Taslim Shodan"),
    SaveAndQuit("Save And Quit", "Zakhire va Khoroog"),
    BlackAndWhite("Black & White", "Siah va Sefid"),
    CheatCodes("Cheat Codes", "Kod haye Rahnama"),
    Time("TIME", "ZAMAN"),
    Level("LEVEL", "Sath"),
    Heart("HEART", "Ghalb"),
    Elder("ELDER", "Ghool"),
    FastShot("FAST SHOT", "Tir Sarii"),
    PressMReduceTime("Press M reduce 1 minute from time!", "M bezan, 1 daghighe az zaman kam mishe!"),
    PressNLevelUp("Press N to level up!", "N bezan, level mirafae!"),
    PressLIncreaseHP("Press L to increase your HP!", "L bezan, HP miaad bala!"),
    PressPSummonElder("Press P to summon the ELDER!", "P bezan, Boss ro seda kon!"),
    PressOIncreaseFireRate("Press O to increase fire rate!", "O bezan, sorat tir bala mire!"),
    ChooseCharacterAndGun("Choose your character and gun: ", "Character va gun khod ra entekhab konid:"),
    Guns("Guns:", "Tirandazha:"),
    GameTime("Game Time:", "Zaman bazi:"),
    SelectedGun("Selected Gun: ", "Tir entekhab shode: "),
    SelectedCharacter("Selected Character: ", "Shakhsiyat entekhab shode: "),
    SelectedGameTime("Selected Game Time: ", "Zaman bazi entekhab shode: "),
    Back("Back", "Bargasht"),
    Play("Play", "Bazi kon"),
    ChangeUsername("Change Username", "Taghir Username"),
    ChangePassword("Change Password", "Taghir Ramz"),
    DeleteUser("Delete User", "Hazf Karbar"),
    Avatar("Avatar", "Avatar"),
    Password("Password", "Password"),
    Register("Register", "Sabt Nam"),
    Login("Login", "Vorod"),
    ContinueAsGuest("Continue as guest", "Edame be onvan Mehman"),
    ForgetPassword("Forget password", "Faramosh Kardane Ramz"),
    TopPlayers("Top Players", "Bazikonanan Bartar"),
    Sort("Sort", "Mortabsazi"),
    ByUsername("by Username", "baraasase Nam-e Karbari"),
    ByKills("by Kills", "baraasase Koshteha"),
    ByScore("by Score", "baraasase Emtiyaz"),
    BySurvival("by Survival", "baraasase Moddat Zamane Baghya"),
    SfxOn("Sfx On", "Sfx Ro Shoroo Kon"),
    AutoReload("Auto Reload", "Relod Kardan-e Khodkar"),
    SelectBackgroundMusic("Select Background Music:", "Musiqi-ye Zamine Ra Entekhab Konid:"),
    ChangeKeyboardKeys("Change keyboard keys:", "Taghir Kelid-haye Keyboard:"),
    Up("Up", "Bala"),
    Down("Down", "Paen"),
    Left("Left", "Chap"),
    Right("Right", "Rast"),
    Reload("Reload", "Relod"),
    Language("Language", "Zaban"),
    BlackWhite("Black&White?", "Siah-o Sefid?"),
    MusicVolume("Music Volume", "Volyume Musiq")
    ;

    private String english;
    private String finglish;
    Texts(String english, String finglish) {
        this.english = english;
        this.finglish = finglish;
    }
    public String getText() {
        if(App.getInstance().getSettings().getLanguage() == Languages.English)
            return english;
        return finglish;
    }
}
